apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schema-registry
  namespace: nm-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      enableServiceLinks: false
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:7.4.0
        # securityContext:
        #   runAsUser: 0
        #   runAsGroup: 0
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schema-registry"
        # - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
        #   value: "nm-kafka-cluster-zookeeper-client.nm-kafka:2181"
        - name: SCHEMA_REGISTRY_LISTENERS
          value: "http://0.0.0.0:8081"
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "nm-kafka-cluster-kafka-bootstrap.nm-kafka:9092"
        volumeMounts:
          - mountPath: /etc/schema-registry/secrets
            name: schema-storage
  volumeClaimTemplates:
    - metadata:
        name: schema-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: standard
        # storageClassName: worker02-nfs-storageclass

---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: nm-kafka
spec:
  ports:
    - name: tpc
      port: 8081
      targetPort: 8081
  selector:
    app: schema-registry
  type: NodePort