# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nm-broker-pv
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 5Gi
#   # storageClassName: standard
#   storageClassName: worker02-nfs-storageclass

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nm-broker-pvc
  namespace: nm-kafka-cdc
spec:
  resources:
    requests:
      storage: 5Gi 
  accessModes:
    - ReadWriteOnce
  storageClassName: worker02-nfs-storageclass

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
  namespace: nm-kafka-cdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:7.4.0
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 9092
        - containerPort: 29092
        - containerPort: 9101
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_JMX_PORT
          value: "9101"
        volumeMounts:
          - mountPath: /var/lib/kafka/data
            name: broker-storage
      volumes:
        - name: broker-storage
          persistentVolumeClaim:
            claimName: nm-broker-pvc
  # volumeClaimTemplates:
  #   - metadata:
  #       name: broker-storage
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 2Gi
  #       storageClassName: worker02-nfs-storageclass

---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: nm-kafka-cdc
spec:
  ports:
    - name: client
      port: 9092
      targetPort: 9092
    - name: internal
      port: 29092
      targetPort: 29092
    - name: jmx
      port: 9101
      targetPort: 9101
  selector:
    app: broker
  type: NodePort
